### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by NdYAG** [r7kamura/draft-js-markless-plugin#3]
Thank you for this plugin! It saves a lot of time to create a WYSIWYG markdown editor.
But I could not find this plugin on npm, https://www.npmjs.com/search?q=draft-js-markless-plugin

Even though I can install this package via git url, it would be more convenient via npm.

Thank you again for your work!

**Comment by r7kamura** [comment]
@NdYAG oh, I forgot to publish it to npm. Thanks!
https://www.npmjs.com/package/draft-js-markless-plugin
